resolver: lts-23.19
packages:
- cursor-dirforest
- cursor-dirforest-gen
- cursor-dirforest-brick
extra-deps:
- github: NorfairKing/dirforest
  commit: a2f160b424f15cea1888d30cc07f02daf75630d9
  subdirs:
  - dirforest
  - genvalidity-dirforest
- github: NorfairKing/cursor-brick
  commit: 7f682cdbf4d79c6aadd10a8141461f177dc8f027
  subdirs:
  - cursor-brick
- github: NorfairKing/cursor
  commit: ae8727c0109d0706019413b36095b50541f37e5a
  subdirs:
  - cursor
  - cursor-gen
system-ghc: true 
nix:                    
  enable: false       
with-hpack: hpack

