resolver: lts-14.23
packages:
- cursor-dirforest
- cursor-dirforest-gen
- cursor-dirforest-brick
- cursor-dirforest-demo
extra-deps:
- github: NorfairKing/dirforest
  commit: c0657315e01683558a8f20b991bc47d4733ed40e
  subdirs:
  - dirforest
  - genvalidity-dirforest
- github: NorfairKing/cursor-brick
  commit: 58b2c811c721885eaa3c066b41bc4d4883e4566c
  subdirs:
  - cursor-brick
- github: NorfairKing/cursor
  commit: f0a17f78d619c34280e326ca6968cda4438c6d75
  subdirs:
  - cursor
  - cursor-gen
- github: NorfairKing/validity
  commit: b8c4cb4cafef7eb2feabaf767eb0d96c5fb5b573
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz"]
  add-gc-roots: true
  pure: true
  packages:
  - zlib

