resolver: lts-14.23
packages:
- cursor-dirforest
- cursor-dirforest-gen
- cursor-dirforest-demo
- ../dirforest/dirforest
- ../dirforest/genvalidity-dirforest
- ../cursor/cursor
- ../cursor/cursor-gen
extra-deps:
- cursor-brick-0.1.0.0
# - github: NorfairKing/cursor
#   commit: f9439d72d714a3eda34aaa8dd83ea4ff2976bce8
#   subdirs:
#   - cursor
#   - cursor-gen
- github: NorfairKing/validity
  commit: 3d5bccbaac055164311ca9d90b0ac7ff7f2c412c
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

