resolver: lts-20.25
packages:
- cursor-dirforest
- cursor-dirforest-gen
- cursor-dirforest-brick
extra-deps:
- github: NorfairKing/dirforest
  commit: a2f160b424f15cea1888d30cc07f02daf75630d9
  subdirs:
  - dirforest
  - genvalidity-dirforest
- github: NorfairKing/cursor-brick
  commit: 7f682cdbf4d79c6aadd10a8141461f177dc8f027
  subdirs:
  - cursor-brick
- github: NorfairKing/cursor
  commit: ae8727c0109d0706019413b36095b50541f37e5a
  subdirs:
  - cursor
  - cursor-gen
- github: NorfairKing/validity
  commit: 20ddbd625304817694b7ae9dc8751f7456259dd6
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
system-ghc: true 
nix:                    
  enable: false       
with-hpack: hpack

