name:                cursor-dirforest
version:             0.0.0.0
github:              "NorfairKing/cursor-dirforest"
license:             MIT

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-redundant-constraints
  dependencies:
  - base >= 4.7 && < 5
  - containers
  - cursor
  - deepseq
  - dirforest
  - microlens
  - validity
