name:                cursor-dirforest-gen
version:             0.0.0.0
github:              "NorfairKing/cursor-dirforest"
license:             MIT

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - cursor
  - cursor-gen
  - cursor-dirforest
  - dirforest
  - genvalidity
  - genvalidity-containers
  - genvalidity-dirforest

tests:
  cursor-dirforest-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dirforest
    - hspec
    - genvalidity-hspec
    - QuickCheck
    - cursor-gen
    - cursor-dirforest
    - cursor-dirforest-gen

benchmarks:
  cursor-dirforest-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - criterion
    - genvalidity-criterion
    - cursor-dirforest
    - cursor-dirforest-gen
